### ISSUE TITLE
[BUG] type is not a TypeInstance in some cases

### ISSUE THREAD

**Issue by kallisto56** [beefytech/Beef#2078]
Hi there,

This code reaches `Debug.WriteLine`, when next workspace properties are set to:
- Dynamic Cast Check: No;
- Object Debug Flags: No;

```C#
namespace bug.IsTypeInstance;

using System;
using System.Diagnostics;
using System.Reflection;

class Program
{
	static void Main ()
	{
		for (var e in System.Type.Types)
		{
			var type = e.GetType();

			if (typeof(TypeInstance) == type && (e is TypeInstance) == false)
			{
				Debug.WriteLine("(typeof(TypeInstance) == type && (e is TypeInstance) == false)");
			}
		}
	}
}
```

Here is the content of `BeefSpace.toml`:
```toml
FileVersion = 1
Projects = {"bug.IsTypeInstance" = {Path = "."}}

[Workspace]
StartupProject = "bug.IsTypeInstance"

[Configs.Debug.Win64]
EmitDynamicCastCheck = false
EnableObjectDebugFlags = false

```

Tested on 0.43.5 (nightly 12/10/2024, https://github.com/beefytech/Beef/commit/3c7b1ea4b709ba8046563534deda22272b413454)
